### PR TITLE
footer font size 16px

### PR DESCRIPTION
**Pull request by kevin98z**

### CODE REVIEW

**Comment by Spin510** [comment]
Hi Kevin, 

Could you capitalize the subnav categories and link them to their subsections when clicked? 

-Shara

**Comment by Spin510** [comment]
Hi Kevin,

Could you capitalize the subnav categories and link them to their subsections when clicked?

-Shara

**Comment by sagarwal10** [comment]
I am not allowed to use my lap top by family right now but I can only look
at code on my phone right now and it looks right. I hope when you shrink
your window you see an accordion. Thanks you for commenting everyone else
but I didn't want to not at least respond after making so much noise.
Thanks everyone.

**Comment by sagarwal10** [comment]
And to Shara's feedback that the second nav goes to the right section in
desktop view. Thank you everyone.

**Pull request merged**
